### ISSUE TITLE
LED dimming

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-PHAL-plugin-mk2#7]
Consider a setting for LED brightness or tie to screen backlight as planned for Mycroft Mk2

https://chat.mycroft.ai/community/pl/5jmfbrj8y78qujakynqdoz51bo

**Comment by j1nx** [comment]
I agree. I like the feedback given in that message.

**Comment by NeonDaniel** [comment]
Relevant bus messages from [brightness plugin](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-brightness-control-rpi):
```python
        self.bus.on("phal.brightness.control.get", self.query_current_brightness)
        self.bus.on("phal.brightness.control.set", self.set_brightness_from_bus)
```

**Comment by NeonDaniel** [comment]
Plugin deprecated, issue created in replacement plugin repo
