### ISSUE TITLE
SJ201 Version Detection

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-PHAL-plugin-mk2#8]
This plugin should be updated to detect dev kit vs production hardware. Mycroft reference implementation is available: https://github.com/MycroftAI/mark-ii-hardware-testing

**Comment by j1nx** [comment]
The detection of production is done via the LED ring of it being different.

I would say;
1) SJ201 mic / board detected -> Load drivers etc. However that is more something for the under lying OS.
2) Old Led ring detected (devkit) -> Load PHAL for that ring
3) No ring detected (prod unit) & SJ201 detected - > Load PHAL for that ring

As the new ring on the production unit is just a NeoPixel device, I guess it could even be extended for any other NeoPixel devices.

**Comment by NeonDaniel** [comment]
Hmm.. I guess the question there is if the production NeonPixel ring would exist outside of the SJ201 board.. We also have the switches handled here, so I'm not sure how much we want to split this up; we could break the `MycroftLed`/`MycroftSwitch` classes and associated stuff into a separate dependency for other plugins?
